# Generated by Django 6.0.4 on 2026-04-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=50, unique=True, verbose_name='Số hiệu công văn')),
                ('title', models.TextField(verbose_name='Trích yếu nội dung')),
                ('doc_type', models.CharField(choices=[('IN', 'Công văn đến'), ('OUT', 'Công văn đi'), ('INT', 'Công văn nội bộ')], max_length=5, verbose_name='Loại công văn')),
                ('status', models.CharField(choices=[('draft', 'Dự thảo'), ('pending', 'Đang xử lý'), ('signed', 'Đã ký/Ban hành'), ('archived', 'Đã lưu trữ')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('sender_org', models.CharField(max_length=255, verbose_name='Cơ quan ban hành/gửi')),
                ('receiver_org', models.CharField(max_length=255, verbose_name='Cơ quan nhận')),
                ('date_issued', models.DateField(verbose_name='Ngày ban hành')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Ngày tiếp nhận/tạo')),
                ('file_attachment', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Tệp tin đính kèm')),
                ('content_extracted', models.TextField(blank=True, verbose_name='Nội dung trích xuất (OCR)')),
            ],
            options={
                'verbose_name': 'Công văn',
                'verbose_name_plural': 'Danh sách Công văn',
            },
        ),
    ]
