"""
Django settings for abc_core project.

Generated by 'django-admin startproject' using Django 6.0.4.

Configuration documentation:
- Settings reference: https://docs.djangoproject.com/en/6.0/ref/settings/
- Deployment checklist: https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
"""

import os
import sys
from pathlib import Path

# ============================================================================
# Path Configuration
# ============================================================================
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# ============================================================================
# Security Settings
# ============================================================================
# WARNING: Keep SECRET_KEY secret! Use environment variables in production.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-dh=^3p*fqye@pl_w6%1#9)10p0i)q@)eyq@=b*wy-1+k_@s&!9'
)

# DEBUG must be False in production
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

# Configure allowed hosts from environment or default to empty
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')


# ============================================================================
# Application Definition
# ============================================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party applications
    'crispy_forms',
    'crispy_bootstrap5',

    # Local Django applications
    'vn_users',
    'vn_docs',
    'vn_workflow',
]

# Crispy Forms configuration for Bootstrap 5
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# ============================================================================
# Middleware Configuration
# ============================================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'abc_core.urls'

# ============================================================================
# Template Configuration
# ============================================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI application
WSGI_APPLICATION = 'abc_core.wsgi.application'


# ============================================================================
# Database Configuration
# ============================================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ============================================================================
# Password Validation
# ============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
]

# Custom user model
AUTH_USER_MODEL = 'vn_users.User'


# ============================================================================
# Internationalization (i18n)
# ============================================================================
LANGUAGE_CODE = 'vi'  # Vietnamese language

TIME_ZONE = 'Asia/Ho_Chi_Minh'  # Vietnam timezone

USE_I18N = True  # Enable internationalization

USE_TZ = True  # Enable timezone support


# ============================================================================
# Static Files & Media Configuration
# ============================================================================
STATIC_URL = 'static/'  # URL for static files
MEDIA_URL = '/media/'  # URL for media uploads
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Filesystem path for media


# ============================================================================
# Celery Configuration
# ============================================================================
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE


