# Generated by Django 6.0.4 on 2026-04-13 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vn_docs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên quy trình')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quy trình duyệt',
                'verbose_name_plural': 'Các quy trình duyệt',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Thứ tự bước')),
                ('name', models.CharField(max_length=100, verbose_name='Tên bước (ví dụ: Trưởng phòng duyệt)')),
                ('role_required', models.CharField(choices=[('admin', 'Quản trị'), ('clerk', 'Văn thư'), ('manager', 'Lãnh đạo'), ('staff', 'Nhân viên')], max_length=20, verbose_name='Vai trò yêu cầu')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='vn_workflow.workflowdefinition')),
            ],
            options={
                'verbose_name': 'Bước quy trình',
                'verbose_name_plural': 'Các bước quy trình',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DocumentWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='vn_docs.document')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vn_workflow.workflowdefinition')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vn_workflow.workflowstep')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Duyệt'), ('reject', 'Từ chối')], max_length=20)),
                ('comment', models.TextField(blank=True, verbose_name='Ý kiến xử lý')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doc_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='vn_workflow.documentworkflow')),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vn_workflow.workflowstep')),
            ],
        ),
    ]
