# Generated by Django 6.0.4 on 2026-04-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vn_workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalhistory',
            name='signature_data',
            field=models.TextField(blank=True, null=True, verbose_name='Dữ liệu ký số'),
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='action',
            field=models.CharField(choices=[('approve', 'Duyeting'), ('reject', 'Từ chối')], max_length=20),
        ),
    ]
